#!/usr/bin/env bash
alias ls='ls -G'

BREW_PREFIX=$(brew --prefix)
export BREW_PREFIX

#If present, use macvim from brew
if [ -x "${BREW_PREFIX}"/bin/mvim ]; then

	for prg in vim view vimdiff vimex
	do
		alias "$prg"="/usr/local/bin/m${prg} -v"
	done
	#ToDo: Either stop using 'vi' or find a better way to do this
	alias vi="/usr/local/bin/mvim -v"
fi
