#!/usr/bin/env python

import socket
import argparse
import subprocess

TCP_IP = '127.0.0.1'
TCP_PORT = 3920

DESKTOPS = {
    1: 'terminal',
    2: 'personal_irc',
    3: 'personal_web',
    4: 'misc_float',
    5: 'misc_bsp',
    6: 'conference',
    7: 'auth',
    8: 'work_irc',
    9: 'work_web',
    10: 'development',
    11: 'email',
    12: 'calendar',
    -1: 'unknown'
}

ACTIVE_WINDOW_SCRIPT = """
global frontApp, frontAppName, windowTitle

set windowTitle to ""
tell application "System Events"
    set frontApp to first application process whose frontmost is true
    set frontAppName to name of frontApp
    tell process frontAppName
        tell (1st window whose value of attribute "AXMain" is true)
            set windowTitle to value of attribute "AXTitle"
        end tell
    end tell
end tell

return {frontAppName & " - " & windowTitle}
"""


def get_current_desktop():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect((TCP_IP, TCP_PORT))
        s.send(b'get _active_desktop')
        return int(s.recv(1024))
    except Exception:
        return -1

def get_current_window():
    try:
        p = subprocess.Popen(['/usr/local/bin/chunkc', 'tiling::query', '--window', 'tag'], 
                             stdin=subprocess.PIPE, stderr=subprocess.PIPE)
        stdout, stderr = p.communicate()
        if not p.returncode:
            print(stderr)
        return ''
    except Exception:
        raise
        return ''


def get_current_profile():
    return 'laptop'


def parse_args():
    parser = argparse.ArgumentParser(prog='chunkwm-query')
    parser.add_argument('-d', '--desktop', help="query active desktop", default=False, action='store_true')
    parser.add_argument('-w', '--window', help="query active window", default=False, action='store_true')
    parser.add_argument('-p', '--profile', help="query active profile", default=False, action='store_true')
    return parser.parse_args()


def main():
    args = parse_args()
    if args.desktop:
        print(DESKTOPS[get_current_desktop()])
    elif args.window:
        print(get_current_window())
    elif args.profile:
        print(get_current_profile())


if __name__ == '__main__':
    main()
