#!/usr/bin/env bash

export PATH=/opt/homebrew/bin:$PATH
GPG_TTY=$(tty)
export GPG_TTY
gpgconf --launch gpg-agent
SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
export SSH_AUTH_SOCK
export MOSH_TITLE_NOPREFIX
mosh emma.mindolo.net -- tmux a -t irc -d
