#!/usr/bin/env bash

export PATH=/Users/fpedrini/.asdf/shims:/Users/fpedrini/.asdf/bin:/Users/fpedrini/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/fpedrini/go/bin:/Users/fpedrini/.fzf/bin
GPG_TTY=$(tty)
export GPG_TTY
gpgconf --launch gpg-agent
SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
export SSH_AUTH_SOCK
export MOSH_TITLE_NOPREFIX
/usr/local/bin/mosh emma -- tmux a -t irc -d
