#!/usr/bin/env bash

GPG_TTY=$(tty)
export GPG_TTY
/usr/local/bin/gpgconf --launch gpg-agent
SSH_AUTH_SOCK=$(/usr/local/bin/gpgconf --list-dirs agent-ssh-socket)
export SSH_AUTH_SOCK

/usr/local/bin/mosh emma -- tmux a -t irc -d
