#!/bin/bash
set -ue
if [[ ${KWM_PROFILE_DEBUG:+1} ]] ; then
  set -x
fi

# configurations
BASE_DIR=/Users/${USER}/.kwm
LIBS_DIR=${BASE_DIR}/libs
PROFILE_DIR=${BASE_DIR}/profiles
KWM_CONFIG_TEMPLATE=${BASE_DIR}/kwmrc.tmpl
KHD_CONFIG_TEMPLATE=${BASE_DIR}/khdrc.tmpl
KWM_CONFIG_FILE=${BASE_DIR}/kwmrc
KHD_CONFIG_FILE=/Users/${USER}/.khdrc
VALID_PROFILES=$(find $PROFILE_DIR -type f -or -type l -name '*.sh' -exec basename {} \; |cut -d'.' -f1|xargs)

source ${LIBS_DIR}/kwm_functions.sh

# usage
function usage {
  echo "usage: $0 <profile>"
  echo "Usable profiles:"
  pretty_profiles ${VALID_PROFILES}
}

# command line argument check
case $# in
  0) # if no arguments are passed detect the current profile and print it
    current_profile=$(cat ${KWM_CONFIG_FILE} |grep include|cut -d'/' -f2 |cut -d'.' -f1)
    echo ${current_profile}
    exit 0
  ;;
  1) # if there is an argument it must be a valid profile.
    PROFILE=${1}
    if [[ "${VALID_PROFILES}" =~ "${PROFILE}" ]]; then
      switch_profile ${PROFILE}
      exit 0
    else
      echo "No such profile '${PROFILE}'."
      echo "Usable profiles:"
      pretty_profiles ${VALID_PROFILES}
      exit 1
    fi
  ;;
  *)
    usage
    exit 2
  ;;
esac
